### PR TITLE
Added new library 'prop-types'

### PR DESCRIPTION
**Pull request by aribronstein**
#33

### CODE REVIEW

**Comment by nkbt** [comment]
I suggest to make all these changes in one PR, there is no need to split it to multiple =)

**Comment by aribronstein** [comment]
sorry, I just made the changes in the online editor and there did not seem to be a way to merge the patches into on PR

**Comment by nkbt** [comment]
You can choose your patch branch and edit more files.

**Comment by aribronstein** [comment]
updated #37 closing other PR's

**Comment by nkbt** [comment]
Thanks 👍

**Pull request closed without merging**
